"""create tables.

Revision ID: 047fe3fa6125
Revises:
Create Date: 2026-10-01 19:49:42.296598
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "047fe3fa6125"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "level_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("level_id", sa.Integer(), nullable=False),
        sa.Column("secret_code", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("level_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_level_attempts_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "guesses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("guess", sa.String(length=64), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["level_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guesses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_guesses_attempt_id"), ["attempt_id"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("unfiltered_content", sa.Text(), nullable=True),
        sa.Column("suspicion", sa.Integer(), nullable=True),
        sa.Column("blocked_by_filter", sa.Boolean(), nullable=False),
        sa.Column("used_fallback", sa.Boolean(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("llm_calls", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["level_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_attempt_id"), ["attempt_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_messages_created_at"), ["created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_created_at"))
        batch_op.drop_index(batch_op.f("ix_messages_attempt_id"))

    op.drop_table("messages")
    with op.batch_alter_table("guesses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guesses_attempt_id"))

    op.drop_table("guesses")
    with op.batch_alter_table("level_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_level_attempts_session_id"))

    op.drop_table("level_attempts")
    op.drop_table("sessions")
    # ### end Alembic commands ###
